### ISSUE TITLE
Characters per LOC

### ISSUE THREAD

**Issue by mkraft** [bbatsov/ruby-style-guide#207]
Is anyone finding their Ruby code becomes less readable/concise in order to conform to the 80-character limit?

Does the original intent of the 80-character limit still achieve the goal of best readability or has it become a hinderance to that goal?

Github's code views fit 101 character without horizontal scrolling; should we be upping the characters per LOC from 80 to 100?

**Comment by bf4** [comment]
Interestingly, the 80char limit was in the first commit https://github.com/bbatsov/ruby-style-guide/commit/dc31232fe357d08039fb59a66199b189cd7aa605

**Comment by Karunamon** [comment]
Holy old debates batman! :)

The problem I'm running into here, and what led to the google search that turned this discussion up, are some real world instances where adhering to the <80 limit merely increases complexity.

Some real code from an app I'm working on (names sanitized):

```ruby
  # @return [ApplicationAPI::Connection] The logged-in ApplicationAPI object.
  # @todo Possibly try extending ApplicationAPI::Connection to do the test on initialization
  # @raise [RuntimeError] if the API login fails for any reason
  def api_authorize
    ib_user = Application::Configuration.get_username
    ib_host = Application::Configuration.get_password
    ib_pass = Application::Configuration.get_host
    c = ApplicationAPI::Connection.new(username: ib_user, password: ib_pass, host: ib_host)
    # We need to make sure the credentials are valid since we don't authenticate
    # until actually doing something with the connection.
      fail RuntimeError 'Unable to log in!' unless ApplicationAPI::Network.all(c, :_max_results => 1).nil?
  end
```

As written, this bombs on lines 2, 4 and 7.

Line 2 is a YARD docstring, and AFAIK, you can't split those across lines.

Fixing line 4 would require adding a new line where a credentials hash is defined, and passing that in to Connection.new. A new line, mostly useless, all to save 7 characters.

Fixing line 7 is interesting. I could fix the line length by changing the one liner to an "if" statement, but then I get yelled at for using an "if-thing-throw-exception" block, and i'm told to change it back to a guard clause, which was the original way it was done. Which means I'd need to define another var, containing the results of the Network.all return, and check it, adding another line to save 23 characters.

At this point, I'm dangerously close to hitting the max function guideline.

Considering I'm using an automated tool to check for these, and my test suite includes a check to make sure all of the style tests pass (rubocop :D), this situation *sucks*.

Consensus among my colleagues is that 80 characters is a relic of a bygone era and introduces more complexity and lengthens methods for no real good reason.

Just another perspective. :+1: if this is revised!

**Comment by halilim** [comment]
@Karunamon agreed, I daily keep running into similar issues with Rubocop < 80. I'm known to do  even more monstrous things for situations like line 7:

      fail RuntimeError 'Unable to log in!' \
        unless ApplicationAPI::Network.all(c, :_max_results => 1).nil?

As you pointed out, these grow to ridiculous proportions over time; so I've started following more practical and readable ideas rather than the ones solely based on some set of rules.

By the way, I'm doing 100 chars/line for quite some time and it seems OK.

**Comment by onebree** [comment]
I think that 100 characters is a good compromise between the original 80 characters and the Github Diff 120 characters. The extra 20 spaces can be useful when there is a lot of indentation present

**Comment by johnthagen** [comment]
+1 for 100 characters as compromise for a hard limit.  For what it's worth, Rust went with the 99: https://aturon.github.io/style/whitespace.html

**Comment by andy-twosticks** [comment]
FWIW: I've been experimentally trying 100 instead of 80.  I'm not having any scrolling problems on my tiny netbook when I code at home -- and I'm finding that it makes the code more readable.

100% in favour of a strict limit here -- and I think anything more than 100 is **much** less readable, it means you are expressing too many ideas in a single line -- but I'm going to switch to 100 now.

**Comment by dakull** [comment]
Almost three years later: I now tend to agree to the 100 chars hard-limit.

Looking at my own code there are cases where it hits ~87-96 characters, I don't really like how it looks so it might get refactored to around 80c-90c though the cost to do that can be high i.e. starting to refactor a couple of classes just because one line of code is too long.

**Comment by mentero** [comment]
I personally prefer 80 chars as I am often using side-by-side views on my rather small 13'' screen but I tend to treat it as soft limit. 80 chars is the goal I try to achieve but I setup my editor to a 100 to give myself a small buffer as I don't want my editor to complain for a minor violation of this rule.

Therefore I vote for a 100 as a hard limit.

**Comment by mmzoo** [comment]
I'm wondering whether [Github's Big Data](https://github.com/blog/2298) can be used to see how many repositories on Github override the default value of `Metrics/LineLength` in their `.rubocop.yml` and to what :)
