### ISSUE TITLE
Whitespace before trailing conditional

### ISSUE THREAD

**Issue by giddie** [bbatsov/ruby-style-guide#321]
Before a trailing conditional, it seems common to use a single space:

```ruby
puts 'hello' if true
```

I suggest that further visual separation should be recommended in this case, by using two spaces:

```ruby
puts 'hello'  if true
```

In my opinion, this makes the conditional stand out from the statement, making it harder to miss. It seems that the style guide does not overtly express any opinion on whitespace before trailing conditionals right now; it would be good to get a decision, I think.

**Comment by GBH** [comment]
:-1: double space is silly

**Comment by giddie** [comment]
@GBH Holy unqualified judgement, Batman!

**Comment by philoserf** [comment]
:-1:

**Comment by bbatsov** [comment]
Closing due to lack of support.

**Comment by kliuless** [comment]
@giddie It's good to find someone else who likes 2 spaces for postfix conditionals. (I thought I was the only one who does this!) I prefer it because it calls attention to the fact that control-flow is happening on the line, which could easily be missed when visually scanning.

But it doesn't seem like a common enough practice for the style guide to enforce it. I'm happy enough that rubocop doesn't disallow the practice.
