### ISSUE TITLE
Rules how/when/not to use `system()`

### ISSUE THREAD

**Issue by onebree** [bbatsov/ruby-style-guide#428]
http://ruby-doc.org/core-1.9.3/Kernel.html#method-i-system

I found this while trying to do variable interpolation in command-line arguments. My first attempt was
```ruby
path = "/home/hstevens/Downloads"
`cp /home/hstevens/test.txt #{path}`
# => ""
```
It worked, but returned `""` -- seems a little sloppy to me.

While researching, I found `system()`, which takes your argument as a string. It makes sense to me to use that, since interpolation is usually (if not always) seen in strings.

I just wanted some advice, as the best use for `system()`, and when to use backticks over it.

**Comment by onebree** [comment]
I am guessing there is no single convention to follow on this?

**Comment by Ajedi32** [comment]
No convention. Those methods do different things. Use backticks when you want to get the result in string form, use `system` when you want the output to go to stdout, and **never** use string interpolation to insert user input into a command (though it's okay to use it to interpolate variables which the user has no ability to influence the contents of).

**Comment by onebree** [comment]
@Ajedi32 Wait, wait, wait... Can you clarify, maybe with examples? I thought that the purpose of both commands were to perform CLI commands (within a Ruby program). There are times I see backticks, other times `system()`, and even at times I see `%x()`. Also, thank you for taking the time to answer

**Comment by Ajedi32** [comment]
As you noticed, backticks return the (stdout) output of whatever command you're executing:

```ruby
x = `echo test`
#=> "test\n"
```

`%x()` is the same, but allows the use of backticks in the command without messing anything up. The rules for when to use `%x()` in place of backticks are [already in the styleguide](https://github.com/bbatsov/ruby-style-guide#percent-x).

`system` doesn't capture output at all. It just executes the command and returns success/failed status. Output from the command goes to stdout.

```ruby
x = system("echo test")
#=> true
```

Output:

```text
test
```

As with any `eval`-like command, you should never use interpolation to insert user input. This is bad:

```ruby
your_name = gets
system("echo Hello, #{gets}!")
```

Because if the user enters `; rm -rf /` when prompted, then you're screwed.

Instead, ensure you're passing user input as an argument, not as part of the command:

```ruby
your_name = gets
system("echo", "Hello, #{your_name}!")
```

I'm not sure I'd really consider this a style issue, as it essentially boils down to "use the method that does what you want" and "don't leave your self open to remote code execution vulnerabilities". Idk though.

**Comment by onebree** [comment]
Okay, the last part of your examples is similar to SQL injection. I learned that it is best to do `"name like ?", "Mr. #{name}"`. I guess it is the same principle. I should research more on why this makes a difference.

Why does the system example output `test`, but the backticks example outputs `test\n`?

I understand that this issue is not necessarily style based, but I thought this would be a good place to ask.

**Comment by Ajedi32** [comment]
`\n` is an escape character that means "new line". If you run `puts` on that string you'll see what I mean.

**Comment by onebree** [comment]
Okay, so you are calling puts on x in both cases? Why would you call puts on `system` since it executes a command?

**Comment by Ajedi32** [comment]
No, I'm not calling puts in any of those examples. I was suggesting that you try `puts "test\n"` in irb, as a way of illustrating my point about what `"\n"` means in Ruby.

Actually I just tried it and it turns out that's not very helpful, since `puts` adds an extra newline character to the output if there isn't one. Try `print "test"`, `print "test\n"`, and `print "test\n\n"` instead.

`\n` just means "new line".

**Comment by onebree** [comment]
I understand what `\n` means. I do not know why `echo test` produces the new line, according to your example.

I will gladly close this issue if you could point me to some resources about `system()`, `%x()`, and using backticks.

**Comment by Ajedi32** [comment]
`echo test` produces a new line because that's how the echo command behaves. It outputs a trailing newline after the text you give it, unless you pass it the `-n` option.

[`system`](http://ruby-doc.org/core/Kernel.html#method-i-system) is a method on the Kernel object. Here's a link to the documentation: http://ruby-doc.org/core/Kernel.html#method-i-system

Backticks are covered here: http://ruby-doc.org/docs/ruby-doc-bundle/Manual/man-1.4/syntax.html#command

There's also a few blog posts and SO questions on this topic:

http://blog.bigbinary.com/2012/10/18/backtick-system-exec-in-ruby.html
https://stackoverflow.com/questions/6338908/ruby-difference-between-exec-system-and-x-or-backticks

**Comment by onebree** [comment]
Thank you very much!
