### ISSUE TITLE
(No) discussion

### ISSUE THREAD

**Issue by LavirtheWhiolet** [bbatsov/ruby-style-guide#480]
A bit harsh but true. Sorry for russian, I'm too lazy to translate.

0 . Всем по###. Каждая софтверная компания придумывает свою стандартную библиотеку и свой style guide.
1 . `FooError = Class.new(StandardError)` — сразу на###. Ибо не единообразно и не сопровождаемо: попробуйте добавить новый метод в обычное двустрочное объявление класса и в **это**. Не нравится пердолить много классов без тел — юзай метапрограммирование.
2 . Присвоение результатов условий лучше писать так:
```
result =
  if some_cond
    x
  else
    y
  end
```
3 . `::` — <font size="large">нинужно</font>. Это костыль для C/C++, утащенный япошкой с совершенно непонятной целью. На деле — нехер плодить сущности.
4 . `?:`, `!`, `&&`, `||` по сравнению с `if-then-else`, `not`, `and`, `or` — нечитаемая ссанина. Их разница в приоритете с их читаемыми аналогами на деле почти не ощущается (а если расставлять скобки вокруг булевых выражений как положено — то совсем не ощущается). `?:` — это вообще костыль для C/C++ (там `if-then-else` — это statement, а нужно было еще expression), бездумно скопированный Ларри исключительно ради краткости, а потом **просто** бездумно скопированный Юкихиро.
5 . Multiline methods chaining:
```    
list.
  select { |man| man.age >= 18 }.
  map { |man| man.salary }.
  reduce(:+)
```
6 . `->(a, b) { ... }` я ##ал в любом виде. Пока япошка не осилит хотя бы C#-овский синтаксис, об альтернативе `lambda { ... }` нечего и думать.
7 . `l.call(...)` — это костыль для парсера, не умеющего в `def ()` и `l()`. Матц дал вам сначала `l[]`, потом поколдовал над парсером и дал что-то похожее на нормальную аппликацию — пользуй, пользуй `l.()`! «Не хочу, хочу жрать `l[]` и `l.call()`»! Что такое?
8 . «Use `$stdout`/`$stderr`/`$stdin` instead of `STDOUT`/`STDERR`/`STDIN`» — а не наоборот ли часом? Предупреждения же в случае переприсвоения констант выдаются, а не глобальных переменных.
9 . «When designing class hierarchies make sure that they conform to the Liskov Substitution Principle», «Try to make your classes as SOLID as possible», «Prefer duck-typing over inheritance» и с подобным пошёл на^W в другое место. Это style guide, а не учебник по программированию. Я ничего не имею против этих советов, просто им здесь не место.
9.1 . Отдельный луч поноса автору и комьюнити за «prefer duck-typing instead of hierarchy».

**Comment by bbatsov** [comment]
> A bit harsh but true. Sorry for russian, I'm too lazy to translate.

I'm not sure what you're expecting to happen. If someone wants to discuss any of the rules, they are welcome to do so, but the discussion should be started in English.

**Comment by philoserf** [comment]
In aid of communication I offer this Google Translate assisted version of the opening statement. It is far from perfect but ... here it is.

0. All of ### . Each software company comes up with a standard library and a style guide.
1. `FooError = Class.new (StandardError)` - directly at ### . For it is not uniform and maintainability : Try to add a new method in the conventional two-line classified in this class . I do not like _________ many classes without bodies - ______ metaprogramming .
2. Assignment conditions better to write the results as follows:

```ruby
result =
  if some_cond
    x
  else
    y
  end
```

3. `:: `- _________ . It is a crutch for the C / C ++, _______ _____ with the aim of completely incomprehensible . In fact - _____ produce essence.
4. `?:`,`!`, `&&`, `||` , Compared with `if-then-else`, `not`, `and`, `or` - ______ unreadable . Their difference in priority from their readable equivalents in fact almost non-existent ( as if to place parentheses around the Boolean expressions as it should be - that is not there ) . `?:` - It is generally a crutch for the C / C ++ ( there `if-then-else` - this statement, and it was necessary even expression), mindlessly copied Larry solely for the sake of brevity , and then just mindlessly copied _____ .
5. Multi-line methods chaining:

```ruby
list.
  select { |man| man.age >= 18 }.
  map { |man| man.salary }.
  reduce(:+)
```

6. `-> (a, b) {...}` I'm ## al in any form. While ___ not master even C # syntax -_____ , an alternative `lambda {...}` can not even think .
7. `l.call (...)` - it is a crutch for the parser , not knowing how to `def ()` and `l()`. Matz gave you first `l[]`, then conjured over the parser and gave what looked like a normal application - behalf, `l.()`! " I do not want , I want to eat `l[]` and `l.call()`"!
8. "Use `$stdout` / `$stderr` / `$stdin` instead of `STDOUT` / `STDERR` / `STDIN`" - and not vice versa Do hour? Warnings same in the case of reassignment constants are issued , rather than global variables.
9. "When designing class hierarchies make sure that they conform to the Liskov Substitution Principle", "Try to make your classes as SOLID as possible", "Prefer duck-typing over inheritance" and with such ^ W went to another place . This style guide, not a textbook on programming. I have nothing against these tips, they just do not belong here .
  9.1. Separate ray diarrhea author and community for "prefer duck-typing instead of hierarchy".

**Comment by bbatsov** [comment]
Haha. I think the Russian version made more sense to me. :-)

**Comment by LavirtheWhiolet** [comment]
A better translation.

0 . Nobody gives a ####. Every software company invents its own standard library and a style guide.
1 . (answered) FooError = Class.new(StandardError) — instant #### you. For it's not uniform and not maintainable: try to add a new method into a commond two-line class declaration and into **this**. If you don't like to crap out many classes without bodies then use metaprogramming.
2 . Assignment of condition results is better to be written as follows:
```
result =
  if some_cond
    x
  else
    y
  end
```
3 . `::` — <font size="5">not needed</font>. This is a cludge from C/C++ borrowed by the Jap for a copletely unknown's sake. In practice—there is no ####ing need to produce entities.
4 . `?:`, `!`, `&&`, `||` versus `if-then-else`, `not`, `and`, `or` is an unreadable urine. Their difference of priority is almost insensible in practice (and if one arranges brackets around the boolean expressions as one is supposed to then it is **completely** insensible). `?:` is just a cludge for C/C++ (`if-then-else` is a statement there but they also needed an expression) which is thoughtlessly copied by Larry for brevity's sake exclusively, and then it is **just** thoughtlessly copied by Yukihiro.
5 . Multiline methods chaining:
```
list.
  select { |man| man.age >= 18 }.
  map { |man| man.salary }.
  reduce(:+)
```
6 . I ####ed `->(a, b) { ... }` in any form. Until the Jap overcomes at least C# syntax, there is nothing to think about alternatives to `lambda { ... }`.
7 . `l.call(...)` is a cludge for the parser which can not into `def ()` and `l()`. Matz first gave you `l[]` and then he conjured over the parser and gave you something looking like a normal application—use, use `l.()`! “No, I don't want that, I want to fress `l[]` and `l.call()`!” What's that?
8 . “Use `$stdout`/`$stderr`/`$stdin` instead of `STDOUT`/`STDERR`/`STDIN`”—isn't it the other way round, by chance? The warnings are printed in case of the reassignment of constants, not of the global variables, after all.
9 . With “When designing class hierarchies make sure that they conform to the Liskov Substitution Principle”, “Try to make your classes as SOLID as possible”, “Prefer duck-typing over inheritance” etc. you go to h^W another place. It is a style guide, not a programmer's tutorial. I have nothing against these advices, there is just no place for them here.
9.1 . A separate ray of diarrhea to the author and the community for “prefer duck-typing instead of hierarchy”.

**Comment by onebree** [comment]
@bbatsov please lock this issue, and possibly flag it. (IDK if that is possible on Github.) Thank you.
