### ISSUE TITLE
Why is case indentation style different from every other block style?

### ISSUE THREAD

**Issue by rantler** [bbatsov/ruby-style-guide#561]
I'm honestly curious about why the community has chosen to reify this exception to the indentation style. It seems to be the only case where a block is _not_ indented one level deeper than the enclosing `keyword/end` combination. It seems that most other languages indent the contents of the `case` or `switch` block as the case may be. Does anyone have any insight as to why this exception is the preferred style?

**Comment by dbenhur** [comment]
Can't speak for the community, but to my mind, it's because the `case` and `when` clauses are syntactic and semantic peers in this control flow grammar. The body of the when clauses are the inferior blocks, but the when clause itself carries as much weight and meaning as the opening case.

Think by analogy with the indentation for if...else.  You would not indent the `else` further than the level of the opening `if`; likewise each `when` and `else` of a `case` is a peer of the opening case clause. If the first of these is wrong, than so is the second:
```ruby
if predicate?
  foo
  else
    baz
end

case val
  when x
    foo
  when y
    bar
  else
    baz
end

**Comment by rantler** [comment]
To my eye, the `if` example certainly does look wrong. Of course, no `if` statement would ever be written like the example below. That's what the unindented `case` statement looks like to my eyes.
```Ruby
if predicate?
else
  bar
end
```
To me though, your `case` example strikes the right balance aesthetically. Another example where I believe the extra indentation works well is:
```Ruby
case val
  when x then 'foo'
  when y then 'bar'
  else 'baz'
end
```

Thanks for the lucid and reasoned response. I understand why this makes sense to some folks. That said, we don't adhere to this particular community style where I work. We use the indented style.

**Comment by dbenhur** [comment]
Many of these style decisions have more than one reasonable answer.  I use the case indentation this guide advocates, but would be perfectly happy doing it in your way @rantler, were that the prevailing style in a code base I was working with. The value of these guides are as examples for beginners and as a point of agreement among collaborators.  There's huge value in having the many contributors to a common code base use **some** consistent style that carries conceptual integrity through it's many point choices, but not a ton of value in any single style choice.

**Comment by rantler** [comment]
My question has been answered, so I'm closing the issue.
